formula = _{ SOI ~ expr ~ EOI }
expr = { term ~ (binop ~ term)* }
term = _{
    proposition
    | negation
    | "(" ~ expr ~ ")"
}
negation = { "¬" ~ term }
binop = _{ conjunction | disjunction | implication | equivalence }
conjunction = { "∧" }
disjunction = { "∨" }
implication = { "→" }
equivalence = { "⇄" }
proposition = @{ (ASCII_ALPHA | "_") ~ (ASCII_ALPHANUMERIC | "_")* }

WHITESPACE = _{ " " | "\t" | "\r" | "\n" }
COMMENT = _{ "/*" ~ (!"*/" ~ ANY)* ~ "*/" }
