name: build

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CARGO_TERM_COLOR: always
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v3
        id: cargo
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
          key: ${{ runner.os }}
      - uses: actions/cache@v3
        id: target
        with:
          path: |
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - uses: dtolnay/rust-toolchain@nightly
        with:
          targets: wasm32-unknown-unknown
      - run: cargo install trunk
        if: steps.cargo.outputs.cache-hit != 'true'
      - name: Build
        run: |
          cd assignment
          trunk build --release
      - uses: actions/upload-artifact@v4
        with:
          path: assignment/dist/
  deploy:
    needs: build
    uses: NKID00/nkid00.name/.github/workflows/deploy.yml@master
    secrets: inherit
