name: Deploy

on:
  push:
    branches:
      - master

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
      - run: cargo install trunk
      - run: trunk build --release
      - uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist/
