name: Deploy

on:
  push:
    branches:
      - master

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
        with:
          targets: wasm32-unknown-unknown
      - run: cargo install trunk
      - run: trunk build --release
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - uses: actions/upload-artifact@v3
        with:
          name: exp1
          path: dist/
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Refresh branch dist
        run: |
          git branch -d dist
          git check out -b dist
          find . -mindepth 1 -maxdepth 1 -not -name .git -exec rm -rf {} +
      - uses: actions/download-artifact@v3
        with:
          path: .
      - name: Push branch dist
        run: |
          git push --force origin dist:dist
