name: deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CARGO_TERM_COLOR: always
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v3
        id: cache
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - uses: dtolnay/rust-toolchain@nightly
        with:
          targets: wasm32-unknown-unknown
      - run: cargo install trunk
        if: steps.cache.outputs.cache-hit != 'true'
      - run: |
          cd assignment/discrete/exp1
          trunk build --release
      - uses: actions/upload-artifact@v3
        with:
          name: exp1
          path: assignment/discrete/exp1/dist/
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure git user
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
      - name: Create branch dist
        run: |
          git checkout -b dist
          find . -mindepth 1 -maxdepth 1 -not -name .git -exec rm -rf {} +
      - uses: actions/download-artifact@v3
        with:
          path: .
      - name: Commit and push branch dist
        run: |
          git add .
          git commit -m "deploy: ${{ github.sha }}"
          git push --force origin dist:dist
